@startuml
hide empty description

[*] -r> s0 : Hauptschalter an /\n setup-Teil
state s0 as "0* Vor-Initialisierung" : Werte in EEPROM schreiben\nwenn nicht vorhanden
s0 --> s1

state s1 as "1* Initialisierung" : Werte aus EEPROM lesen\nWiegezelle initialisieren
s1 -l> s2 : Fehler
s1 -r> s11 : OK /\nÜbergang zu loop

state s2 as "2 Fehler" : Keine Kommunikation\nmit Wiegezelle möglich


state s11 as "11* Schalter Position" : VE-Schalter-Position auslesen\n+ immer Ausgang ausschalten
s11 --> s12 : I
s11 --> s17 : II
s11 -r> s22 : 0

state s12 as "12 Voreinst. 1 (inaktiv)" : 0: Starten\n1: Tara-Versatz 1 bearb.\n2: Sollwert 1 bearb.
s12 -> s13 : 0+OKK

state s13 as "13 VE 1 aktiv" : + Ausgang an
s13 -> s14 : Soll erreicht /\nAbbruch
state s14 as "14 VE 1 fertig" : + ggf. Ton abspielen
s12 <- s14

'
state s17 as "17 Voreinst. 2 (inaktiv)" : 0: Starten\n1: Tara-Versatz 1 bearb.\n2: Sollwert 1 bearb.


' state s4 as "4 Kalibrierung" : Kalibrierung erforderlich\nSensor leeren, dann OK
' state s5 as "5 Kalibrierung" : Gewicht mit bekannter\nMasse auf Sensor,\ndann OK
' state s41 as "41 Tara messen"
' s4 --> s41 : OK
' s41 --> s5
' state s6 as "6 Kalibrierung" : Bekannte Masse eingeben\n0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: 0.01er Stelle\n4: OK/X
' s5 --> s6 : OK
' state s7 as "7 Kalibrierung" : EEPROM Speichern?\n0 :nein\n1: ja
' state s61 as "61 Kalibrierung"
' s6 --> s61 : 4+OK
' s61 --> s7
' state s71 as "71 Werte speichern"
' s7 --> s71
' s71 --> s11
' state s9 as "9 Tara" : Tara erforderlich\nSensor leeren, dann OK
' state s10 as "10 Tara" : EEPROM Speichern?\n0 :nein\n1: ja
' state s91 as "91 Tara messen"
' s9 --> s91 : OK
' s91 --> s10
' state s101 as "101 Tara-Offset speichern"
' s10 --> s101
' s101 --> s11
' 
' 
' s12 --> s11 : Schalter\ngeändert
' 
' s12 --> s13 : 0+lang-OK
' 
' s13 --> s14 : Soll erreicht\n/ Abbruch
' s14 --> s12
' state s15 as "15 Soll-1 bearb." : 0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: OK/X\n+ EEPROM speichern
' s12 --> s15 : 2+OK
' state s151 as "151 VE1 Werte Speichern" : Sollwerte + Tara-Versatz
' s15 --> s151
' state s16 as "16 TV-1 bearb." : 0: 1er Stelle\n1: 0.1er Stelle\n2: 0.01er Stelle\n3: OK/X\n+ EEPROM speichern
' s12 --> s16 : 1+OK
' s16 --> s151
' s151 --> s12
' 
' 
' s17 --> s11 : Schalter\ngeändert
' state s18 as "18 VE 2 aktiv" : + Ausgang an
' s17 --> s18 : 0+lang-OK
' state s19 as "19 VE 2 fertig" : + Ton abspielen
' s18 --> s19 : Soll erreicht\n/ Abbruch
' s19 --> s17
' state s20 as "20 Soll-2 bearb." : 0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: OK/X\n+ EEPROM speichern
' s17 --> s20 : 2+OK
' state s201 as "201 VE2 Werte Speichern" : Sollwerte + Tara-Versatz
' s20 --> s201 : OK
' state s21 as "21 TV-2 bearb." : 0: 1er Stelle\n1: 0.1er Stelle\n2: 0.01er Stelle\n3: OK/X\n+ EEPROM speichern
' s17 --> s21 : 1+OK
' s21 --> s201 : OK
' s201 --> s17

' state s22 as "22 keine VE gewählt" : 0: Start\n1: Einstellungen\n2: Sollwert bearb. 
' 
' s22 --> s11 : Schalter\ngeändert
' state s23 as "23 ohne VE aktiv" : + Ausgang an
' s22 --> s23 : 0+lang-OK
' state s24 as "24 ohne VE fertig" : + Ton abspielen (?)
' s23 -l> s24 : Soll erreicht \n/ Abbruch
' s24 --> s22
' state s25 as "25 Soll-oVE bearb." : 0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: OK/X
' s22 -> s25 : 2+OK
' s25 -> s22 : OK
' state s26 as "26 Einstellungen" : 0: zurück\n1: Tastentöne\n2: Ende-Ton\n3: Tara\n4: Kalibrierung\n5: Zurücksetzen
' s22 --> s26 : 1+OK
' state s28 as "28 Einstellungen speichern"
' s26 --> s28 : 0+OK
' s28 --> s22
' s26 -->s9 : 3+OK
' s26 --> s4 : 4+OK
' state s27 as "27 Zurücksetzen" : Wirklich zurücksetzen?\n0: nein\n1: ja
' s26 --> s27 : 5+OK
' s26 -> s26 : 1|2+OK
' s27 --> s26 : 0+OK
' state s29 as "29 Zurücksetzen" : EEPROM löschen!\nReboot!
' s27 --> s29 : 1+OK
' s29 --> [*]

@enduml