@startuml
hide empty description

' legend top left
' <b>Abkürzungen:</b>
' VE = Voreinstellung
' SW = Soll-Wert
' TV = Tara-Versatz
' Be. = Bearbeiten
' Sp. = Speichern
' end legend

'state S as "Zustandsdiagramm Weight-O-Matic"
'S --> s2


[*] --> s0 : Hauptschalter an /\n setup-Teil
state s0 as "0* Vor-Initialisierung" : Werte in EEPROM schreiben\nwenn nicht vorhanden
s0 --> s1

state s1 as "1* Initialisierung" : Werte aus EEPROM lesen\nWiegezelle initialisieren
s1 -u-> s2 : Fehler
s1 -r> s11 : OK /\nÜbergang zu loop

state s2 as "2 Fehler" : Keine Kommunikation\nmit Wiegezelle möglich

state s11_N <<start>>
s11_N --> s11 : Schalter in anderem\nZustand geändert
state s11 as "11* Schalter Position" : VE-Schalter-Position auslesen\n+ immer Ausgang deaktivieren
s11 --> s12_17 : I / II
s11 -> s22 : 0

state s12_17 as "12 / 17 VE 1 / 2 (inaktiv)" : 0: Starten\n1: Tara-Versatz 1 bearb.\n2: Sollwert 1 bearb.
s12_17 -l-> s13_18 : 0+OKK
s12_17 --> s15_20 : 1+OK
s12_17 --> s16_21 : 2+OK

state s13_18 as "13 / 18 VE 1 / 2 (aktiv)" : Ausgang aktivieren
s13_18 --> s14_19 : Soll erreicht /\nAbbruch
state s14_19 as "14 / 19 VE 1 / 2 (fertig)" : ggf. Ton abspielen
s14_19 -> s12_17 : OK / OKK

state s15_20 as "15 / 20 SW 1 / 2 Be." : 0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: OK
s15_20 -> s151_201 : 3+OK /\nOKK
state s16_21 as "16 / 21 TV 1 / 2 Be." : 0: 1er Stelle\n1: 0.1er Stelle\n2: 0.01er Stelle\n3: OK
s16_21 -l> s151_201 : 3+OK /\nOKK
state s151_201 as "151* / 201* VE 1 / 2 Sp." : Sollwerte + Tara-Versatz\nIns EEPROM speichern
s151_201 -up-> s12_17

state s22 as "22 keine VE (inaktiv)" : 0: Start\n1: Einstellungen\n2: Sollwert bearb.
s22 --> s23 : 0+OKK
s22 -u-> s25 : 2+OK
s22 -> s26 : 3+OK
state s23 as "23 keine VE (aktiv)" : Ausgang aktivieren
s23 --> s24 : Soll erreicht /\nAbbruch
state s24 as "24 keine VE (fertig)" : ggf. Ton abspielen
s24 --> s22 : OK /\nOKK
state s25 as "25 keine VE SW Be." : 0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: OK
s25 -> s22 : 3+OK /\nOKK

state s26 as "26 Einstellungen" : 0: zurück\n1: Tastentöne\n2: Ende-Ton\n3: Tara\n4: Kalibrierung\n5: Zurücksetzen
s26 -u-> s28 : 0+OK
's26 -> s26 : 1/2+OK
s26 -u-> s9 : 3+OK
s26 -> s4 : 4+OK
s26 --> s27 : 5+OK
state s28 as "28* Einstellungen Sp." : Einstellungs-Bitvektor\nins EEPROM schreiben
s28 --> s22

state s27 as "27 Zurücksetzen?" : 0: nein\n1: ja
s27 --> s26 : 0+OK
s27 --> s29 : 1+OK
state s29 as "29* EEPROM Zurücks."
s29 -l-> [*] : Reboot

state s9 as "9 Tara!" : "Sensor leeren,\ndann OK"
s9 -u-> s91 : OK
state s91 as "91* Tara messen"
s91 -l-> s10
state s10 as "10 Tara Sp.?" : 0 :nein\n1: ja
s10 -l-> s101 : 1+OK
s10 --> s11 : 0+OK
state s101 as "101* Tara Sp." : Tara-Wert ins\nEEPROM speichern
s101 ---> s11

state s4 as "4 Kalibrierung!" : "Sensor leeren,\ndann OK"
s4 --> s41
state s41 as "41* Kalib. messen (1)"
s41 --> s5
state s5 as "5 Kalibrierung!" : "Gewicht mit bekannter\nMasse auf Sensor,\ndann OK"
s5 --> s6 : OK
state s6 as "6 Kalibrierung" : "Bekannte Masse eingeben"\n0: 10er Stelle\n1: 1er Stelle\n2: 0.1er Stelle\n3: 0.01er Stelle\n4: OK
s6 -l-> s61 : 4+OK
state s61 as "61* Kalib. messen (2)"
s61 -l-> s7
state s7 as "7 Kalib. Sp.?" : 0 :nein\n1: ja
s7 -u---> s11 : 0+OK
s7 -l-> s71 : 1+OK
state s71 as "71* Kalib. Sp." : Kalib.-Werte ins\nEEPROM schreiben
s71 -u---> s11

note "<b>Abkürzungen:</b>\nVE = Voreinstellung\nSW = Soll-Wert\nTV = Tara-Versatz\nBe. = Bearbeiten\nSp. = Speichern" as N1
note "<b>Markierungen:</b>\n...* : automatischer Übergang in Folgezustand\n       ohne Nutzereingabe\n...! : Nutzer wird aufgefordert, etwas zu tun\n...?: Nutzer muss sich entscheiden" as N2
N1 -[hidden]> N2
N2 -[hidden]> s71

@enduml